version: "3.8"
services:
  db:
    image: postgres:14
    container_name: pomodoro_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pomodoro_app
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
     - nest-net

networks:
    nest-net:

volumes:
    pgdata: